type: custom:xiaomi-vacuum-map-card
map_source:
  camera: image.roborock_qrevo_master_downstairs_custom
calibration_source:
  camera: true
entity: vacuum.roborock_qrevo_master
vacuum_platform: Roborock